#!/usr/bin/env python

import getopt
import json
import sys

# https://gitweb.torproject.org/builders/tor-browser-bundle.git/tree/Bundle-Data/PTConfigs/bridge_prefs.js?id=tbb-5.0.3-build3
TORBROWSER_DEFAULT_BRIDGE_ADDRESSES = (
    "83.212.101.3",
    "169.229.59.74",
    "169.229.59.75",
    "109.105.109.163",
    "192.240.101.106",
    "50.7.176.114",
    "131.252.210.150",
    "128.105.214.161",
    "128.105.214.162",
    "128.105.214.163",
    "2001:49f0:d002:1::2",
    "2001:49f0:d00a:1::c",
    "188.226.213.208",
    "178.209.52.110",
    "104.131.108.182",
)

# These are from default_authorities in src/or/config.c in tor's source code,
# as of tag: tor-0.2.10.
# https://gitweb.torproject.org/tor.git/tree/src/or/config.c?id=tor-0.2.6.10#n848
DIRAUTH_ADDRESSES = (
    "128.31.0.39",      # moria1
    "86.59.21.38",      # tor26
    "194.109.206.212",  # dizum
    "82.94.251.203",    # Tonga
    "131.188.40.189",   # gabelmoo
    "193.23.244.244",   # dannenberg
    "208.83.223.34",    # urras
    "171.25.193.9",     # maatuska
    "154.35.175.225",   # Faravahar
    "199.254.238.52",   # longclaw
)

def usage(f=sys.stdout):
    print >> f, """\
Usage: %s <env> <tb_var> <or_addresses>
  <env> is the censorship environment: "1", "2", or "3".
  <tb_var> is "old" or "new".
  <or_addresses> is the filename of an Onionoo JSON file.\
""" % sys.argv[0]

def read_addresses_from_json(f):
    j = json.load(f)
    addresses = []
    for relay in j["relays"]:
        for or_address in relay["or_addresses"]:
            addr, port = or_address.rsplit(":", 1)
            addr = addr.strip("[]")
            addresses.append(addr)
    return addresses

def read_addresses_from_json_filename(filename):
    with open(filename) as f:
        return read_addresses_from_json(f)

# How to use the "netsh advfirewall firewall" context instead of the "netsh
# firewall" context to control Windows Firewall behavior in Windows Server 2008
# and in Windows Vista
# https://support.microsoft.com/en-us/kb/947709

def block_ips(name, ips):
    print "netsh advfirewall firewall add rule name=\"%s\" dir=out action=block remoteip=%s" % (name, ",".join(ips))

opts, args = getopt.gnu_getopt(sys.argv[1:], "")
try:
    env, tb_var, or_addresses_filename = args
except ValueError:
    usage(sys.stderr)
    sys.exit(1)

assert env in ("1", "2", "3")

if env in ("3",):
    block_ips("Tor Browser default bridges", TORBROWSER_DEFAULT_BRIDGE_ADDRESSES)

if env in ("2", "3"):
    block_ips("Tor directory authorities", DIRAUTH_ADDRESSES)

    addresses = read_addresses_from_json_filename(or_addresses_filename)
    # There's some limit on netsh command line length; 500 IPs at a time seems
    # not to exceed it.
    for i in range (0, len(addresses), 500):
        slice = addresses[i:i+500]
        block_ips("Tor relays %d-%d" % (i, i+500-1), slice)

if env in ("1", "2", "3"):
    print "copy hosts %SystemRoot%\System32\drivers\etc\hosts" 

# Unpacking the .zip file and installing our programs
#   1. install old or new version of tor
#   2. install chrome 
#   3. install firefox
#   4. install VLC 

# 1 #
if tb_var == "old": 
    print "C:\\Users\\ll-admin\\Desktop\\tor-ux\\torbrowser-old-5.0.3_en-US.exe /S"
elif tb_var == "new": 
    print "C:\\Users\\ll-admin\\Desktop\\tor-ux\\torbrowser-new-5.0.3_en-US.exe /S"
else:
    raise ValueError("tb_var has to be \"old\" or \"new\".")

# 2 #
print "C:\\Users\\ll-admin\\Desktop\\tor-ux\\ChromeSetup.exe /silent /install"

# 3 # 
print "C:\\Users\\ll-admin\\Desktop\\tor-ux\\FirefoxSetup.exe -ms"

# 4 #
# Use the old version of VLC that comes with the desktop image (v 2.1.5)
# print "C:\\Users\\ll-admin\\Desktop\\tor-ux\\vlc-2.2.2-win64.exe /S"


# Setting up the Desktop for the user 
#   chrome, firefox and vlc put shortcuts on desktop on install 
#   tor installer has been modified to put shortcuts on desktop on install 
#   we want all but the VLC shortcuts on the desktop 
# 
#   1. delete VLC shortcut off the desktop 
#   2. copy cursor for screen recording into a fixed place 
#   2. start the screen recording 

# 1 # 
print "del \"C:\\Users\\Public\\Desktop\\VLC media player.lnk\""

# 2 # 
# TODO: fix naming of file, currenty blah.mp4 
# TODO: add in the reduced fps, cursor, and live caching (commented at end)
print "\"C:\\Program Files (x86)\\VideoLAN\\VLC\\vlc.exe\" screen:// --sout=\"#transcode{vcodec=h264,acodec=mpga,ab=128,channels=2,samplerate=44100}:file{dst=blah.mp4,no-overwrite}\" --sout-keep" #--screen-fps 10 --screen-mouse-image=C:\Users\Administrator\ux\cursor.png --live-caching 300



