#!/usr/bin/env python

import getopt
import json
import sys

def usage(f=sys.stdout):
    print >> f, """\
Usage: %s <or_addresses>
  <or_addresses> is the filename of an Onionoo JSON file.\
""" % sys.argv[0]

def read_addresses_from_json(f):
    j = json.load(f)
    addresses = []
    for relay in j["relays"]:
        for or_address in relay["or_addresses"]:
            addr, port = or_address.rsplit(":", 1)
            addr = addr.strip("[]")
            addresses.append(addr)
    return addresses

def read_addresses_from_json_filename(filename):
    with open(filename) as f:
        return read_addresses_from_json(f)

# How to use the "netsh advfirewall firewall" context instead of the "netsh
# firewall" context to control Windows Firewall behavior in Windows Server 2008
# and in Windows Vista
# https://support.microsoft.com/en-us/kb/947709

def remove_firewall_rule(name):
    print "netsh advfirewall firewall delete rule name=\"%s\"" % name

opts, args = getopt.gnu_getopt(sys.argv[1:], "")
try:
    or_addresses_filename, = args
except ValueError:
    usage(sys.stderr)
    sys.exit(1)

upload_dir = "%TEMP%\\upload"
vlc_path = "C:\\Program Files (x86)\\VideoLAN\\VLC"

# https://stackoverflow.com/questions/130116/windows-batch-commands-to-read-first-line-from-text-file/7827243#7827243
print "set /p runid=<runid.txt"
print "\"" + vlc_path + "\\vlc.exe\" --one-instance vlc://quit"
# Give VLC some time to shut down cleanly. Otherwise it doesn't manage to write
# the end of the video file.
print "timeout 20 /nobreak"
print "del /q \"" + upload_dir + "\""
print "rmdir \"" + upload_dir + "\""
print "mkdir \"" + upload_dir + "\""
print "copy \"%runid%.mp4\" \"" + upload_dir + "\""
print "copy \"%USERPROFILE%\\Desktop\\Tor Browser\\Browser\\inst.log\" \"" + upload_dir + "\\%runid%-inst.log\""
print "s3-uploader.exe"

remove_firewall_rule("Tor Browser default bridges")

remove_firewall_rule("Tor directory authorities")

addresses = read_addresses_from_json_filename(or_addresses_filename)
for i in range (0, len(addresses), 500):
    slice = addresses[i:i+500]
    remove_firewall_rule("Tor relays %d-%d" % (i, i+500-1))

print "del %SystemRoot%\System32\drivers\etc\hosts" 

# uninstall Tor Browser 
print "rmdir /Q /S \"%USERPROFILE%\\Desktop\\Tor Browser\""
print "del \"%USERPROFILE%\\Desktop\\Start Tor Browser.lnk\""
