#!/usr/bin/env python

import json
import sys

# Usage:
# wget -O or_addresses.json https://onionoo.torproject.org/details?fields=or_addresses
# ./gen-firewall < or_addresses.json

# Alternate onionoo download: https://onionoo.thecthulhu.com/details?fields=or_addresses

def read_addresses_from_json(f):
    j = json.load(f)
    addresses = []
    for relay in j["relays"]:
        for or_address in relay["or_addresses"]:
            addr, port = or_address.rsplit(":", 1)
            addresses.append(addr)
    return addresses

# How to use the "netsh advfirewall firewall" context instead of the "netsh
# firewall" context to control Windows Firewall behavior in Windows Server 2008
# and in Windows Vista
# https://support.microsoft.com/en-us/kb/947709
def block_ips(ips, name):
    print "netsh advfirewall firewall add rule name=\"%s\" dir=out action=block remoteip=%s" % (name, ",".join(ips))

addresses = read_addresses_from_json(sys.stdin)
block_ips(addresses, "Tor relays")
