#!/usr/bin/env python

# How to use the "netsh advfirewall firewall" context instead of the "netsh firewall" context to control Windows Firewall behavior in Windows Server 2008 and in Windows Vista
# https://support.microsoft.com/en-us/kb/947709

def block_ips(ips, name):
    print "netsh advfirewall firewall add rule name=\"%s\" dir=out action=block remoteip=%s" % (name, ",".join(ips))

block_ips(["192.0.2.1"], "Block example")
