#!/usr/bin/env python

import getopt
import json
import sys

def usage(f=sys.stdout):
    print >> f, """\
Usage: %s 
  this takes no inputs.\
""" % sys.argv[0]

upload_dir = "%TEMP%\\upload"
s_drive = "S:\\lee"
vlc_path = "C:\\Program Files (x86)\\VideoLAN\\VLC"

# Save the files.
#   1. save the video and log onto our amazon s3 servers.  
#   2. back up the logs onto the xlab sdrive (not enough room for videos).

# 1 # 

# https://stackoverflow.com/questions/130116/windows-batch-commands-to-read-first-line-from-text-file/7827243#7827243
print "set /p runid=<runid.txt"
print "\"" + vlc_path + "\\vlc.exe\" --one-instance vlc://quit"
# Give VLC some time to shut down cleanly. Otherwise it doesn't manage to write
# the end of the video file.
print "timeout 20 /nobreak"
print "del /q \"" + upload_dir + "\""
print "rmdir \"" + upload_dir + "\""
print "mkdir \"" + upload_dir + "\""
print "copy \"%runid%.mp4\" \"" + upload_dir + "\""
print "copy \"%USERPROFILE%\\Desktop\\Tor Browser\\Browser\\inst.log\" \"" + upload_dir + "\\%runid%-inst.log\""
print "s3-uploader.exe"

# 2 # 
print "copy \"%runid%.mp4\" \"" + s_drive + "\""